#! /bin/sh
# /etc/init.d/openjabnab
### BEGIN INIT INFO
# Provides:          OpenJabNab Server
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: OpenJabNab Server
# Description:       Launch the OpenJabNab Server
### END INIT INFO
#
# Author: Soif
#########################################################################################

# Set the absolute path to OpenJabNab/server/bin/
OJN_PATH=/home/apache/INT/OpenJabNab/server/bin/

##### DO NOT CHANGE BELOW ###############################################################
NAME=openjabnab
DESC="OpenJabNab Server"
DAEMON=$OJN_PATH$NAME

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# Function that starts the daemon/service #######
do_start()
{
    echo "Starting $DESC...	"
	$DAEMON 2>&1 &
	sleep 0.1
    echo "------------------------------"
    echo "$DESC Started !"
}

# Function that stops the daemon/service #########
do_stop()
{
    echo -n "Stopping $DESC...	"
	killall -q $DAEMON
    echo "OK"
}

# test #################
case "$1" in
  start)
    do_start
    ;;
  stop)
    do_stop
    ;;
  restart)
    do_stop
    do_start
    ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
